# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import andrewmzhang_pulumi_nextdns.config as __config
    config = __config
    import andrewmzhang_pulumi_nextdns.nextdns as __nextdns
    nextdns = __nextdns
else:
    config = _utilities.lazy_import('andrewmzhang_pulumi_nextdns.config')
    nextdns = _utilities.lazy_import('andrewmzhang_pulumi_nextdns.nextdns')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "pulumi-nextdns",
  "mod": "nextdns",
  "fqn": "andrewmzhang_pulumi_nextdns.nextdns",
  "classes": {
   "pulumi-nextdns:nextdns:NextDNSRewrite": "NextDNSRewrite"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "pulumi-nextdns",
  "token": "pulumi:providers:pulumi-nextdns",
  "fqn": "andrewmzhang_pulumi_nextdns",
  "class": "Provider"
 }
]
"""
)
