// Code generated by MockGen. DO NOT EDIT.
// Source: ./nextdns (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -typed -package main -destination mocks.gen.go -imports goprovider=github.com/pulumi/pulumi-go-provider ./nextdns Client
//

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	models "github.com/andrewmzhang/nextdns-go/models"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CheckRewrite mocks base method.
func (m *MockClient) CheckRewrite(profileId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRewrite", profileId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckRewrite indicates an expected call of CheckRewrite.
func (mr *MockClientMockRecorder) CheckRewrite(profileId any) *MockClientCheckRewriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRewrite", reflect.TypeOf((*MockClient)(nil).CheckRewrite), profileId)
	return &MockClientCheckRewriteCall{Call: call}
}

// MockClientCheckRewriteCall wrap *gomock.Call
type MockClientCheckRewriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCheckRewriteCall) Return(arg0 error) *MockClientCheckRewriteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCheckRewriteCall) Do(f func(string) error) *MockClientCheckRewriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCheckRewriteCall) DoAndReturn(f func(string) error) *MockClientCheckRewriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateRewrite mocks base method.
func (m *MockClient) CreateRewrite(profileId, name, content string) (*models.Rewrite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRewrite", profileId, name, content)
	ret0, _ := ret[0].(*models.Rewrite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRewrite indicates an expected call of CreateRewrite.
func (mr *MockClientMockRecorder) CreateRewrite(profileId, name, content any) *MockClientCreateRewriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRewrite", reflect.TypeOf((*MockClient)(nil).CreateRewrite), profileId, name, content)
	return &MockClientCreateRewriteCall{Call: call}
}

// MockClientCreateRewriteCall wrap *gomock.Call
type MockClientCreateRewriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCreateRewriteCall) Return(arg0 *models.Rewrite, arg1 error) *MockClientCreateRewriteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCreateRewriteCall) Do(f func(string, string, string) (*models.Rewrite, error)) *MockClientCreateRewriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCreateRewriteCall) DoAndReturn(f func(string, string, string) (*models.Rewrite, error)) *MockClientCreateRewriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteRewrite mocks base method.
func (m *MockClient) DeleteRewrite(profileId, rewriteId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRewrite", profileId, rewriteId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRewrite indicates an expected call of DeleteRewrite.
func (mr *MockClientMockRecorder) DeleteRewrite(profileId, rewriteId any) *MockClientDeleteRewriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRewrite", reflect.TypeOf((*MockClient)(nil).DeleteRewrite), profileId, rewriteId)
	return &MockClientDeleteRewriteCall{Call: call}
}

// MockClientDeleteRewriteCall wrap *gomock.Call
type MockClientDeleteRewriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientDeleteRewriteCall) Return(arg0 error) *MockClientDeleteRewriteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientDeleteRewriteCall) Do(f func(string, string) error) *MockClientDeleteRewriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientDeleteRewriteCall) DoAndReturn(f func(string, string) error) *MockClientDeleteRewriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRewrite mocks base method.
func (m *MockClient) GetRewrite(profileId, rewriteId string) (*models.Rewrite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRewrite", profileId, rewriteId)
	ret0, _ := ret[0].(*models.Rewrite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRewrite indicates an expected call of GetRewrite.
func (mr *MockClientMockRecorder) GetRewrite(profileId, rewriteId any) *MockClientGetRewriteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRewrite", reflect.TypeOf((*MockClient)(nil).GetRewrite), profileId, rewriteId)
	return &MockClientGetRewriteCall{Call: call}
}

// MockClientGetRewriteCall wrap *gomock.Call
type MockClientGetRewriteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetRewriteCall) Return(arg0 *models.Rewrite, arg1 error) *MockClientGetRewriteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetRewriteCall) Do(f func(string, string) (*models.Rewrite, error)) *MockClientGetRewriteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetRewriteCall) DoAndReturn(f func(string, string) (*models.Rewrite, error)) *MockClientGetRewriteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
