// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Andrewmzhang.Nextdns
{
    /// <summary>
    /// A NextDNS Rewrite into a pulumi resource
    /// </summary>
    [NextdnsResourceType("nextdns:index:NextDNSRewrite")]
    public partial class NextDNSRewrite : global::Pulumi.CustomResource
    {
        /// <summary>
        /// IP Address or Domain to rewrite domain name to.
        /// </summary>
        [Output("content")]
        public Output<string> Content { get; private set; } = null!;

        /// <summary>
        /// Domain name to apply rewrite to.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Profile Id to apply rewrite to. This overrides the default profile id.
        /// </summary>
        [Output("profileId")]
        public Output<string?> ProfileId { get; private set; } = null!;


        /// <summary>
        /// Create a NextDNSRewrite resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NextDNSRewrite(string name, NextDNSRewriteArgs args, CustomResourceOptions? options = null)
            : base("nextdns:index:NextDNSRewrite", name, args ?? new NextDNSRewriteArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NextDNSRewrite(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("nextdns:index:NextDNSRewrite", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NextDNSRewrite resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NextDNSRewrite Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new NextDNSRewrite(name, id, options);
        }
    }

    public sealed class NextDNSRewriteArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// IP Address or Domain to rewrite domain name to.
        /// </summary>
        [Input("content", required: true)]
        public Input<string> Content { get; set; } = null!;

        /// <summary>
        /// Domain name to apply rewrite to.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Profile Id to apply rewrite to. This overrides the default profile id.
        /// </summary>
        [Input("profileId")]
        public Input<string>? ProfileId { get; set; }

        public NextDNSRewriteArgs()
        {
        }
        public static new NextDNSRewriteArgs Empty => new NextDNSRewriteArgs();
    }
}
