# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .next_dns_rewrite import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import andrewmzhang_nextdns.config as __config
    config = __config
else:
    config = _utilities.lazy_import('andrewmzhang_nextdns.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "nextdns",
  "mod": "index",
  "fqn": "andrewmzhang_nextdns",
  "classes": {
   "nextdns:index:NextDNSRewrite": "NextDNSRewrite"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "nextdns",
  "token": "pulumi:providers:nextdns",
  "fqn": "andrewmzhang_nextdns",
  "class": "Provider"
 }
]
"""
)
