// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.andrewmzhang.nextdns;

import com.pulumi.core.internal.Codegen;
import java.lang.String;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("nextdns");
    public String apiKey() {
        return Codegen.stringProp("apiKey").config(config).require();
    }
}
