// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.andrewmzhang.nextdns;

import com.andrewmzhang.nextdns.NextDNSRewriteArgs;
import com.andrewmzhang.nextdns.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * A NextDNS Rewrite into a pulumi resource
 * 
 */
@ResourceType(type="nextdns:index:NextDNSRewrite")
public class NextDNSRewrite extends com.pulumi.resources.CustomResource {
    /**
     * IP Address or Domain to rewrite domain name to.
     * 
     */
    @Export(name="content", refs={String.class}, tree="[0]")
    private Output<String> content;

    /**
     * @return IP Address or Domain to rewrite domain name to.
     * 
     */
    public Output<String> content() {
        return this.content;
    }
    /**
     * Domain name to apply rewrite to.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Domain name to apply rewrite to.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Profile Id to apply rewrite to. This overrides the default profile id.
     * 
     */
    @Export(name="profileId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> profileId;

    /**
     * @return Profile Id to apply rewrite to. This overrides the default profile id.
     * 
     */
    public Output<Optional<String>> profileId() {
        return Codegen.optional(this.profileId);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public NextDNSRewrite(java.lang.String name) {
        this(name, NextDNSRewriteArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public NextDNSRewrite(java.lang.String name, NextDNSRewriteArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public NextDNSRewrite(java.lang.String name, NextDNSRewriteArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nextdns:index:NextDNSRewrite", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private NextDNSRewrite(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nextdns:index:NextDNSRewrite", name, null, makeResourceOptions(options, id), false);
    }

    private static NextDNSRewriteArgs makeArgs(NextDNSRewriteArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? NextDNSRewriteArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static NextDNSRewrite get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new NextDNSRewrite(name, id, options);
    }
}
